version: "3.9"
services:
  avif:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        buildno: 1
    ports:
      - "5000:5000"
    volumes:
      - .:/code
    environment:
      FLASK_ENV: development
